#!/bin/bash

# Trigger Upstart Configuration
# initctl reload-configuration

# Trigger Udev
# udevadm control --reload-rules

# SysVinit
chmod 755  /etc/init.d/mochad_logger
update-rc.d mochad_logger defaults
